### ISSUE TITLE
docker vessel segmentation

### ISSUE THREAD

**Issue by FeynmanDNA** [alceballosa/deform-aneurysm-detection#3]
Hi, very interesting work!

I am curious about your docker for vessel segmentation:

> Vessel segmentation docker image can be downloaded from: https://drive.google.com/file/d/1qa91P423Sp5fMqUUoMxBGV0EUEAQirBC/view

> You then can run docker load -i vessel_seg.tar to make it available in your environment.

The segmentation docker is **26GB** in size. May I know is this docker supposed to be able to segment vessels on any CTA dataset? If so, is there any docker run command to do the inference? Do I make it into a container first?

Thanks!

**Comment by alceballosa** [comment]
Hi!

Thanks for your interest in our work! While we cannot guarantee that the model will perform well on any CTA dataset, the model generalized well from the data used to  train the segmentation network (private) to the data we used to train the aneurysm detection model (Bo's public dataset), thus, we suspect that it will perform comparably on other datasets. Of course, it will depend on your use case. If you can report back how well it works for you that would be very helpful.

Regarding usage, I just pushed and update to the README file adding a section describing how to use the segmentation docker image on its own. Please let me know if you run into any issues.

**Comment by FeynmanDNA** [comment]
Hi!

Nicely done! I will check it the usage. I will also close the issue.
Thanks for the prompt reply!
