### ISSUE TITLE
Issue with Missing Libraries in Reproducing Training Code

### ISSUE THREAD

**Issue by wealone1** [alceballosa/deform-aneurysm-detection#4]
Hi,

Thank you for your excellent work. However, I encountered an issue while trying to reproduce the training and inference code. Specifically, the libraries referenced in the code are not provided, which prevents me from running the training process successfully. For instance:
```python
from src.models.deformable.box_processor import BoxProcessor
from src.models.deformable.generic_mlp import GenericMLP
from src.models.deformable.nms import nms
from src.models.deformable.parq_matcher_rec import HungarianMatcherModified
from src.models.deformable.matcher import HungarianMatcherModified
from src.models.deformable.parq_utils import get_3d_corners
``` 
These references are located in /deform-aneurysm-detection-main/src/models/deformable/def_parq_rec.py. Could you please advise how to resolve this issue or provide the missing code for these libraries?

Thank you for your assistance!

Best regards,
max

**Comment by alceballosa** [comment]
Hi Max,

Thanks for your interest! The issue was related to me refactoring some code and not pushing the changes properly. I think you should be able to run the pipeline successfully with the most recent commit, but let me know if that doesn't work.

Best,

Alberto

**Comment by wealone1** [comment]
Hi Alberto,

Find it！ Thanks for replying promptly！

Best,
Max

**Comment by wealone1** [comment]
Hi,

Thanks to your guidance, I was able to successfully run the detection model and obtain the bounding boxes.

I am now looking into evaluating both the detection and segmentation results. Could you kindly let me know if you have provided any code or scripts in your repository for calculating evaluation metrics shown in your paper? If not, I would greatly appreciate it if you could recommend any tools or approaches for this purpose.

Thank you once again for your amazing work and help. Looking forward to hearing from you.

Best regards,

**Comment by wealone1** [comment]
Hi,

Thanks to your guidance, I was able to successfully run the detection model and obtain the bounding boxes.

I am now looking into evaluating both the detection and segmentation results. Could you kindly let me know if you have provided any code or scripts in your repository for calculating evaluation metrics shown in your paper? If not, I would greatly appreciate it if you could recommend any tools or approaches for this purpose.

Thank you once again for your amazing work and help. Looking forward to hearing from you.

Best regards,
Max

**Comment by alceballosa** [comment]
Hi Max,

I just added instructions for evaluation. They're a first pass so let me know if anything is not super clear there.

Best,

Alberto

**Comment by wealone1** [comment]
Hi Alberto,

Yeah! thanks for your efficient help and  I will try it!

Best,
Max
